export const languageArray = [
  { type: 0, en: "English", ko: "영어" },
  { type: 1, en: "Korean", ko: "한국어" },
  { type: 2, en: "Chinese", ko: "중국어" },
  { type: 3, en: "Arabic", ko: "아랍어" },
  { type: 4, en: "Hindi", ko: "힌두어" },
  { type: 5, en: "Vietnamese", ko: "베트남어" },
  { type: 6, en: "Russian", ko: "러시아어" },
  { type: 7, en: "Japanese", ko: "일본어" },
  { type: 8, en: "Thai", ko: "태국어" },
  { type: 9, en: "Malay", ko: "말레이어" },
  { type: 10, en: "Indonesian", ko: "인도네시아어" },
  { type: 11, en: "Arabic", ko: "아랍어" },
  { type: 12, en: "Bengali", ko: "벵골어" },
  { type: 13, en: "French", ko: "프랑스어" },
  { type: 14, en: "German", ko: "독일어" },
  { type: 15, en: "Spanish", ko: "스페인어" },
  { type: 16, en: "Italian", ko: "이탈리아어" },
  { type: 17, en: "Portuguese", ko: "포르투갈어" },
  { type: 18, en: "Dutch", ko: "네덜란드어" },
  { type: 19, en: "Swedish", ko: "스웨덴어" },
];
